// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Session struct {
	Token     string    `json:"token"`
	TenantID  string    `json:"tenant_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Student struct {
	TenantID string  `json:"tenant_id"`
	ID       int64   `json:"id"`
	Name     string  `json:"name"`
	Gpa      float64 `json:"gpa"`
}

type User struct {
	TenantID     string `json:"tenant_id"`
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}
