// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
insert into sessions (token, tenant_id, user_id, created_at, expires_at)
values ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	TenantID  string    `json:"tenant_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.Token,
		arg.TenantID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createStudent = `-- name: CreateStudent :exec
insert into students (tenant_id, id, name, gpa)
values ($1, $2, $3, $4)
`

type CreateStudentParams struct {
	TenantID string  `json:"tenant_id"`
	ID       int64   `json:"id"`
	Name     string  `json:"name"`
	Gpa      float64 `json:"gpa"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.Exec(ctx, createStudent,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Gpa,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
insert into users (tenant_id, id, email, password_hash)
values ($1, $2, $3, $4)
`

type CreateUserParams struct {
	TenantID     string `json:"tenant_id"`
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.TenantID,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
delete from sessions where expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getSession = `-- name: GetSession :one
select token, tenant_id, user_id, created_at, expires_at from sessions
where token = $1
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.TenantID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
select tenant_id, id, name, gpa from students
where tenant_id = $1 and id = $2
`

type GetStudentParams struct {
	TenantID string `json:"tenant_id"`
	ID       int64  `json:"id"`
}

func (q *Queries) GetStudent(ctx context.Context, arg GetStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, arg.TenantID, arg.ID)
	var i Student
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Name,
		&i.Gpa,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select tenant_id, id, email, password_hash from users
where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
select tenant_id, id, name, gpa from students
where tenant_id = $1
order by id
`

func (q *Queries) ListStudents(ctx context.Context, tenantID string) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.Name,
			&i.Gpa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
